//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FixedFormPackager.Test.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FixedFormPackager.Test.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;nlog xmlns=&quot;http://www.nlog-project.org/schemas/NLog.xsd&quot;
        ///      xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot;
        ///      xsi:schemaLocation=&quot;http://www.nlog-project.org/schemas/NLog.xsd NLog.xsd&quot;
        ///      autoReload=&quot;true&quot;
        ///      throwExceptions=&quot;false&quot;
        ///      internalLogLevel=&quot;Off&quot; internalLogFile=&quot;c:\temp\nlog-internal.log&quot;&gt;
        ///
        ///  &lt;!-- optional, add some variables
        ///  https://github.com/nlog/NLog/wiki/Configuration-file#variables
        ///  --&gt;
        ///  &lt;variable name=&quot;myvar&quot;  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string NLog {
            get {
                return ResourceManager.GetString("NLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] NLog1 {
            get {
                object obj = ResourceManager.GetObject("NLog1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot;?&gt;
        ///&lt;doc&gt;
        ///    &lt;assembly&gt;
        ///        &lt;name&gt;NLog&lt;/name&gt;
        ///    &lt;/assembly&gt;
        ///    &lt;members&gt;
        ///        &lt;member name=&quot;T:JetBrains.Annotations.CanBeNullAttribute&quot;&gt;
        ///            &lt;summary&gt;
        ///            Indicates that the value of the marked element could be &lt;c&gt;null&lt;/c&gt; sometimes,
        ///            so the check for &lt;c&gt;null&lt;/c&gt; is necessary before its usage
        ///            &lt;/summary&gt;
        ///            &lt;example&gt;&lt;code&gt;
        ///            [CanBeNull] public object Test() { return null; }
        ///            public void UseTest() {        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string NLog2 {
            get {
                return ResourceManager.GetString("NLog2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] ProcessSmarterTestPackage {
            get {
                object obj = ResourceManager.GetObject("ProcessSmarterTestPackage", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] ProcessSmarterTestPackage1 {
            get {
                object obj = ResourceManager.GetObject("ProcessSmarterTestPackage1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] SmarterTestPackage_Common {
            get {
                object obj = ResourceManager.GetObject("SmarterTestPackage_Common", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] SmarterTestPackage_Common1 {
            get {
                object obj = ResourceManager.GetObject("SmarterTestPackage_Common1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] TabulateSmarterTestAdminPackage {
            get {
                object obj = ResourceManager.GetObject("TabulateSmarterTestAdminPackage", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;configuration&gt;
        ///    &lt;startup&gt; 
        ///        &lt;supportedRuntime version=&quot;v4.0&quot; sku=&quot;.NETFramework,Version=v4.6.1&quot;/&gt;
        ///    &lt;/startup&gt;
        ///&lt;/configuration&gt;
        ///.
        /// </summary>
        internal static string TabulateSmarterTestAdminPackage_dll {
            get {
                return ResourceManager.GetString("TabulateSmarterTestAdminPackage_dll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;configuration&gt;
        ///    &lt;startup&gt; 
        ///        &lt;supportedRuntime version=&quot;v4.0&quot; sku=&quot;.NETFramework,Version=v4.6.1&quot;/&gt;
        ///    &lt;/startup&gt;
        ///&lt;/configuration&gt;
        ///.
        /// </summary>
        internal static string TabulateSmarterTestAdminPackage_exe {
            get {
                return ResourceManager.GetString("TabulateSmarterTestAdminPackage_exe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;configuration&gt;
        ///    &lt;startup&gt; 
        ///        &lt;supportedRuntime version=&quot;v4.0&quot; sku=&quot;.NETFramework,Version=v4.6.1&quot;/&gt;
        ///    &lt;/startup&gt;
        ///&lt;/configuration&gt;
        ///.
        /// </summary>
        internal static string TabulateSmarterTestAdminPackage_vshost_exe {
            get {
                return ResourceManager.GetString("TabulateSmarterTestAdminPackage_vshost_exe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] TabulateSmarterTestAdminPackage_vshost_exe1 {
            get {
                object obj = ResourceManager.GetObject("TabulateSmarterTestAdminPackage_vshost_exe1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] TabulateSmarterTestAdminPackage1 {
            get {
                object obj = ResourceManager.GetObject("TabulateSmarterTestAdminPackage1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] TabulateSmarterTestPackage {
            get {
                object obj = ResourceManager.GetObject("TabulateSmarterTestPackage", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///
        ///&lt;configuration&gt;
        ///  &lt;startup&gt;
        ///    &lt;supportedRuntime version=&quot;v4.0&quot; sku=&quot;.NETFramework,Version=v4.6.1&quot; /&gt;
        ///  &lt;/startup&gt;
        ///&lt;/configuration&gt;.
        /// </summary>
        internal static string TabulateSmarterTestPackage_exe {
            get {
                return ResourceManager.GetString("TabulateSmarterTestPackage_exe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] TabulateSmarterTestPackage_vshost {
            get {
                object obj = ResourceManager.GetObject("TabulateSmarterTestPackage_vshost", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///
        ///&lt;configuration&gt;
        ///  &lt;startup&gt;
        ///    &lt;supportedRuntime version=&quot;v4.0&quot; sku=&quot;.NETFramework,Version=v4.6.1&quot; /&gt;
        ///  &lt;/startup&gt;
        ///&lt;/configuration&gt;.
        /// </summary>
        internal static string TabulateSmarterTestPackage_vshost_exe {
            get {
                return ResourceManager.GetString("TabulateSmarterTestPackage_vshost_exe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] TabulateSmarterTestPackage_vshost_exe1 {
            get {
                object obj = ResourceManager.GetObject("TabulateSmarterTestPackage_vshost_exe1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] TabulateSmarterTestPackage1 {
            get {
                object obj = ResourceManager.GetObject("TabulateSmarterTestPackage1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] ValidateSmarterTestPackage {
            get {
                object obj = ResourceManager.GetObject("ValidateSmarterTestPackage", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] ValidateSmarterTestPackage1 {
            get {
                object obj = ResourceManager.GetObject("ValidateSmarterTestPackage1", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
